version: '3.8'
services:
  db:
    container_name: cheffy_db
    image: postgres:14-alpine
    ports:
      - 5435:5432
    environment:
      - POSTGRES_USER=cheffy
      - POSTGRES_DB=cheffy
      - POSTGRES_PASSWORD=cheffy
    volumes:
      - ./.database-data/data:/var/lib/postgresql/data/
volumes:
  database-data:
